//maps/hldm_revenant.bsp
maps/hldm_revenant.res
maps/hldm_revenant.txt
//sprites/jinx/jx0firesmall.spr
//sprites/jinx/m_orflare1.spr
//sound/jinx/borg_rain.wav
//sound/jinx/jxfirecamp.wav
//sound/jinx/jxthunder01.wav
//sound/jinx/jxthunder02.wav
//sound/jinx/mr_rain1.wav
models/jinx/garg_gibs.mdl
models/jinx/wik_gat.mdl
models/jinx/wik_gmn.mdl
models/jinx/wik_readme.txt
gfx/env/dmcpup.tga
gfx/env/dmcprt.tga
gfx/env/dmcplf.tga
gfx/env/dmcpft.tga
gfx/env/dmcpdn.tga
gfx/env/dmcpbk.tga